on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Get release version
      run: |
          TAG=${{ github.ref_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: |
          echo ${{ github.ref_name }} > assets/data/version.txt
          chmod u+x gradlew
          ./gradlew html:dist
          rm -rf html/build/dist/WEB-INF
          mv html/build/dist/functions html/build
          cd html/build
          mv dist joric-web-${{ github.ref_name }}
          zip -r joric-web-${{ github.ref_name }}.zip joric-web-${{ github.ref_name }}
          cd ../..
          mv html/build/joric-web-${{ github.ref_name }}.zip .
          ./gradlew lwjgl3:jar
          mv lwjgl3/build/lib/joric-${VERSION}.jar joric-desktop-${VERSION}.jar

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          joric-*.*
